apiVersion: v1
kind: ReplicationController
metadata:
  name: my-app-rc
  labels:
    app: my-app
    tier: backendd
spec:
  template:
    metadata:
      name: my-app
      labels:
        tier: backend
    spec:
      containers:
        - name: nginx
          image: nginx

  replicas: 3

  # selector:
  #   matchLabels:
  #     tier: backend
