apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-app-replicaset
  labels:
    app: my-app
    tier: backend
spec:
  template:
    metadata:
      name: my-app
      labels:
        app: my-app
        tier: backend
    spec:
      containers:
        - name: nginx
          image: nginx

  replicas: 6
  selector:
    matchLabels:
      tier: backend
