apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - name: webserver
      targetPort: 80
      port: 90
      nodePort: 30008

    - name: webserver2
      targetPort: 80
      port: 100
      nodePort: 30009
  selector:
    app: myapp
    tier: backend
